---
# These are defaults of role1

# we want to override this var in role2
role2_var: role1

# we are not going to override role2_var2
# role2_var2: role1

# this only exists in role1 and should get passed to role2 automatically
random_var: role1

# alternative way is you prefix your defaults for the parent role
role1_role2_var: role1