---
# This playbook shows how a parent role's defaults can override the default variables of a child role
- name: Failing Examples
  hosts: localhost
  tasks:
    - name: "Include Failing Parent Role #1"
      include_role: 
        name: parent-role-fail1
        
- name: Working Examples
  hosts: localhost
  tasks:
    - name: "Include Success Parent Role #1"
      include_role: 
        name: parent-role-success1