---
# This set_fact creates and object with variables that you want to put inside as keys
- name: Define child_role object vars for use in include_role
  set_fact:
    child_role: "{{ child_role | default({}) | combine({ item: lookup('vars', item) }) }}"
  when: lookup('vars', item, default='UNDEFINED_VARIABLE') != 'UNDEFINED_VARIABLE'
  loop:
    - child_role_var
    - child_role_var2

- name: "Include child-role. If you never specify a value for child_role_var2, it will not use the defaults of child-role/defaults/main.yml since you passed it via the 'vars:' statement"
  include_role: 
    name: child-role
  vars:
    child_role_var: "{{ child_role.child_role_var }}"
    child_role_var2: "{{ child_role.child_role_var2 | default('parent-role did not specify a value for child_role_var2') }}"