---
- name: Include Role 2. This will not override the defaults of role2
  include_role: 
    name: role2

- name: Include Role 2, specify vars to pass. This will fail due to using the same var name.
  include_role: 
    name: role2
  vars:
    role2_var: "{{ role2_var }}"