---
# This set_fact creates and object with variables that you want to put inside as keys
- name: Define child_role object vars for use in include_role
  set_fact:
    child_role: "{{ child_role | default({}) | combine({ item: lookup('vars', item) }) }}"
  when: lookup('vars', item, default='UNDEFINED_VARIABLE') != 'UNDEFINED_VARIABLE'
  loop:
    - child_role_var

- name: Include child-role. This WILL override the defaults of child-role
  include_role: 
    name: child-role
  vars:
    child_role_var: "{{ child_role.child_role_var }}"

# You could just prefix all your role1 defaults like parent_child_role_var
# But I prefer to keep the var names the same across parent and child roles
- name: Include child-role but use a prefixed parent_role variable
  include_role: 
    name: child-role
  vars:
    child_role_var: "{{ parent_child_role_var }}"